### ISSUE TITLE
this guy(or girl) copied my bookmarklets

### ISSUE THREAD

**Issue by Nakul-Ardeshana** [inyourface34456/bookmarklets-website#4]
why man(or woman), whyyyyy
i didn't say u couldn't use them but atleast credit me for some of [my work](https://github.com/Nakul-Ardeshana/Bookmarklets/)

this is not a bug this is just a public report

also you readme file is grammatically incorrect (it is here not hear(hear means listen or something))

**Comment by inyourface34456** [comment]
Sorry!!! i will give you credit!!

**Comment by inyourface34456** [comment]
BTW, i think this is [Fair Use](https://fairuse.stanford.edu/overview/fair-use/what-is-fair-use/).  You never mentioned anything about giving you credit.  i have included all comments giving credit to the person.

**Comment by Nakul-Ardeshana** [comment]
but it's obvi right man or woman(or both, I do not want to sound rude)

**Comment by Nakul-Ardeshana** [comment]
also if you want you can include tis bookmarklet:-
`javascript:location.replace('https://www.'+prompt('website url?'));`

**Comment by inyourface34456** [comment]
@Nakul-Ardeshana, do you want to be a contributor?  All i need is to keep finding bookmarklets.

**Comment by Nakul-Ardeshana** [comment]
yea you still have many grammatical mistakes you can check them on Grammarly
